project:
  type: website

execute:
  # Store output of executed code cells in the `_freeze` directory, and
  # re-render them only when the source changes.
  freeze: auto

website:
  title: "Erwin Janssen"
  navbar:
    right:
      - icon: github
        href: https://github.com/ErwinJanssen/
      - icon: mastodon
        href: https://mastodon.social/@erwinjanssen
      - icon: linkedin
        href: https://www.linkedin.com/in/ejjanssen/
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
